remote_theme: pages-themes/cayman@v0.2.0
title: "OnTheCatsTrail"
description: OnTheCatsTrail — это увлекательный 2D платформер, в котором игроки берут на себя роль героя, который должен спасти котов, попавших в бедственное положение. Исследуйте красочные уровни, преодолевайте препятствия и сражайтесь с врагами, чтобы вернуть котов домой!

